// src/tree-view.tsx
import React, { FC } from "react";
import { TreeNode } from "./types";

type TreeViewProps = {
    root: TreeNode;
}
export const TreeView: FC<TreeViewProps> = ({ root }) => {
    return (<li>
        {root.title}
        {root.children.length > 0 && (<div className={"list-container"}>
            <ul>
                {root.children.map((child: TreeNode) => <TreeView root={child}/>)}
            </ul>
        </div>)}
    </li>);
};

// src/TreeView.vue
<script setup lang="ts">
import "./TreeView.style.css";
import { type Node } from "./types";

const { root } = defineProps<{ root: Node }>();
</script>
<template>
  <li>
    <div class="list-item">{{ root.title }}</div>
    <div v-if="root.children.length > 0" class="list-container">
      <ul>
        <TreeView v-for="child in root.children" :key="child.id" :root="child" />
      </ul>
    </div>
  </li>
</template>
